### ISSUE TITLE
Achive a project that is ready to be shared and publish

### ISSUE THREAD

**Issue by jurra** [Robotic-Building-TU-Delft/dcc-collab#3]
# Projects needs to be archived in some repository like 4TU or zenodo
## Checklist:
- [x] In which format it should be archived
- [x] Try in the sandbox in Zenodo

## Todos
- [x] Start with the circular wood project
- [x] Provide Files where the data can be download
- [x] Try zenodo sandbox
- [x] Try the 4TU repository

**Comment by jurra** [comment]
# A follow up on archiving issues
- Can we append other items in the dataset on top of github integration? I fear that if ou archive code with the release integration is going to be unlikely this can happen. One solution could be @MaxLatour and @vrnk to create a collection that stores different parts of the data set, say for instance a collection for Tool path generator that contains one upload with videos, one upload with actual data assets or data set, and one item with the code. It doesn't sound ideal, but at least this can work
- How should we store large files? We could use DVC or LFS. At the same time, we could aim as a policy to leave only the main branch and perhaps develop, and the rest of ancillary branches to be temporary, destined to be deleted once such increments are finished or merged into the master branch.

**Comment by MaxLatour** [comment]
The archive template has been uploaded to Github and 4TU:
https://github.com/Robotic-Building-TU-Delft/Archive-Template
https://figshare.com/s/70b783e4bf13852b6f56

The archive of the CW4N not yet, because it contains large files.

**Comment by jurra** [comment]
@vrnk and @MaxLatour  A note on archiving with 4TU (figshare):
The process doesn't happen automatically, we have either:
1. Manually select the version you want.
2. Configure github actions in your repository to publish automatically your next release.


You have to setup a figshare personal token for yourself: https://help.figshare.com/article/how-to-get-a-personal-token
This is how you setup github action for automatic publishing in 4TU: https://github.com/figshare/github-upload-action
 
Another final note: Figshare is the service provider of 4TU so, figshare is what powers the 4TU data portal. This means you are actually using figshare when you are archiving, uploading etc.

**Comment by jurra** [comment]
**Figshare automatically updates after a next release if auto-sync is on:**
> A key aspect of setting Github up via the applications section is that you can edit the auto-sync global settings for your github integration. If you configure the auto-sync setting to ON, figshare will automatically update for every release (for each of your imported repos) and this will only occur if your figshare item is public. Each new release would generate a new version of your figshare item.

**Comment by jurra** [comment]
We added the gcode generator, @MaxLatour got a response of 4TU on how to improve it.
